
version: '3.8'
services:
  # 청산 데이터 수집 전용 서비스
  liquidation-service:
    build: ./backend/liquidation_service
    ports:
      - "8001:8001"
    volumes:
      - ./backend/liquidation_service:/app
    environment:
      - PORT=8001
    restart: unless-stopped

  # 코인 가격 수집 전용 서비스  
  coinprice-service:
    build: ./backend/coinprice_service
    ports:
      - "8002:8002"
    volumes:
      - ./backend/coinprice_service:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=8002
      - DATABASE_URL=mysql+pymysql://user:password@db/kimchiscan
    restart: unless-stopped

  # 기존 백엔드는 API 게이트웨이 역할로 축소
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      liquidation-service:
        condition: service_started
      coinprice-service:
        condition: service_started
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db/kimchiscan
      - LIQUIDATION_SERVICE_URL=http://liquidation-service:8001
      - COINPRICE_SERVICE_URL=http://coinprice-service:8002
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    stdin_open: true
    tty: true
    depends_on:
      - backend
      - liquidation-service
      - coinprice-service
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
      - REACT_APP_LIQUIDATION_SERVICE_URL=http://localhost:8001
      - REACT_APP_COINPRICE_SERVICE_URL=http://localhost:8002
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: kimchiscan
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

volumes:
  mysql-data:
